language: node_js
node_js:
  - "node"
warnings_are_errors: false
install:
  - npm install
script:
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "q3gcKKb0Zzd1OYy05Q3TJwSef5LNHBspii86M0xZRvFPfGShx3wbeB2ah2JO1qoJlAmB+p8LqkZo54P/c9VCQGi8IZGa4ViF3cLo7s0CUdR8cQmgyGOBZsgbcV5tNpCc6DCiXXPNEx2O8fzWEqsF2JnJz53HAfVwfd4uRRbg99OI4D5fjN0L1luW3sksTLFQA2AlilPD/ryul5wTr/0HEU3j+Gdo4PsPpO1wtN7J6A0qgToXVJGzg0v9nVqzifvZi54c/rHSFlaKoLeWicE0BP7vodok/Gb0tVmaSpbGHYQOX+Y6usIa6+rQSZ8EzUvXvZ4RTIVb3o/RUnMklgdOZ/yhWcH9H24Jj8a34vPUEZva4Uhq0OMhJIGnQH1OT/DFHgrY6kh8f7u71U2dbyGAUkVPQF16n1bVwKSLj9jwWWFiQqVoJd5kMBF//cUvY+/f3zcRamKRIvjZiYqK3AxZWUMYmYxeXPsTOs238SKe2iDc+UdOkIEMcKeFLxFwKl/VAOoI/BVWHdyhF52uRVQ/oC1RjFywF6qpf16p2PPL29TZHrrckKGYyJOXLC5LPFTP22U5eCCGcYGVwKQKw9sLEDjzHvIjI46E0493WfOaDUEafWSEtFuVEj2e/tEuVR3GTePkxmHw13gs2j0nw95dhQC5YH4aXJDykGK3jr54QCg="